### ISSUE TITLE
Update verisigner to use tkey-libs

### ISSUE THREAD

**Issue by dehanj** [tillitis/tkey-verification#14]
Verisigner is dependent on tillitis-key1-apps repo, but the dependencies has been move to tkey-libs.

**Comment by dehanj** [comment]
in progress #15

**Comment by dehanj** [comment]
Build scripts should also be updated.

**Comment by AkechiShiro** [comment]
Hi @dehanj is there any branch of the repo where there are more recent commits

**Comment by dehanj** [comment]
Hi @AkechiShiro, 
The branch `use_tkeylibs` has some later commits. But, be aware tkey-libs has more changes not reflected in that branch either yet, it is on the todo-list. If you use the commit 94b3d12 of tkey-libs verisigner should be buildable at its current state.

But if your intention is to verify your TKey, I would recommend using a [release ](https://github.com/tillitis/tkey-verification/releases/tag/v0.0.2) which has pre-compiled binaries to download and run.

**Comment by dehanj** [comment]
Closing this issue. Verisigner is beeing deprecated and tkey-device-signer will be used instead. 
Verisigner will live on in the older tags of this repo.
